### ISSUE TITLE
添加填报地址等信息

### ISSUE THREAD

**Issue by xzz024** [insorasky/HFUT_auto_submit#2]
大佬如何自己添加填报地址等信息，谢谢。如果有可不可以添加些注释👀

**Comment by insorasky** [comment]
这个是用的网页版的接口，网页版的接口不会通过GPS获取你的位置信息，也就不会提交地址。
目前网页版的接口未发现位置信息的提交入口。
~~我们学院的话没有地址导员也不会怎样啦（~~
如果需要相关功能，我会尽量解决。

**Comment by xzz024** [comment]
<img width="832" alt="截屏2021-08-14 13 21 33" src="https://user-images.githubusercontent.com/68104786/129435052-2d270d28-71c7-4884-9ba4-1af6636e5747.png">
但是我发现这里可以填入地址，但它只在网页版显示，手机版好像不是那么有效，谢谢
